# lis3mdl_calibration_parameters.py
"""
lis3mdl hard-iron calibration parameters, does not include soft iron calibration,
since only compass directions used.

Compass headings (atan2) computes the angle differences of X- and Y-values.
The Soft-iron calibrations would make sure the vector lengths are calibrated, which doesn't affect the angle.

CONSTANTS generated by:
    hard_only_calibrate_lis3mdl_test.py

Creates
 * scale factors to normalize the field to a 1.0 radius
 * offsets based on calibration constants - true magnetic midpoint offset for X and Y
"""
CALIBRATED_MAG_MIN = [-58.7548, -38.7898, -102.2800]
CALIBRATED_MAG_MAX = [44.9284, 63.4171, -4.4870]

X_OFFSET = (CALIBRATED_MAG_MAX[0] + CALIBRATED_MAG_MIN[0]) / 2.0
Y_OFFSET = (CALIBRATED_MAG_MAX[1] + CALIBRATED_MAG_MIN[1]) / 2.0
X_SCALE = (CALIBRATED_MAG_MAX[0] - CALIBRATED_MAG_MIN[0]) / 2.0
Y_SCALE = (CALIBRATED_MAG_MAX[1] - CALIBRATED_MAG_MIN[1]) / 2.0